FROM golang:1.12-alpine as builder

RUN mkdir /build 

ADD . /build/

WORKDIR /build 

RUN apk add build-base git

RUN make build-api

FROM scratch

COPY --from=builder /build/bin/api /
COPY --from=builder /build/templates /templates

EXPOSE 8080

ENTRYPOINT ["/api"]
