FROM golang:1.12-alpine as builder

RUN mkdir /build 

ADD . /build/

WORKDIR /build 

RUN apk add --no-cache build-base git ca-certificates

RUN make build-api

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /build/bin/api /
COPY --from=builder /build/templates /templates

EXPOSE 8080

ENTRYPOINT ["/api"]
