apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: GITHUB_CLIENT_ID
          value: Iv1.4d121e96ec2e71a8
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: GITHUB_TOKEN
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: GITHUB_CLIENT_SECRET
        image: kostarelo/discover-api
        name: api
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /src/local
          name: api-claim0
      restartPolicy: Always
      volumes:
      - name: api-claim0
        persistentVolumeClaim:
          claimName: api-claim0
status: {}
