apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: crawler
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: crawler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: crawler
    spec:
      containers:
      - env:
        - name: QUEUE_STORE_DIR
          value: ./
        - name: REDIS_HOST
          value: redis:6379
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: crawler-secret
              key: GITHUB_TOKEN
        - name: NEO4J_HOST
          valueFrom:
            secretKeyRef:
              name: crawler-secret
              key: NEO4J_HOST
        - name: SUGGESTION_STORE_PWD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: SUGGESTION_STORE_PWD
        image: kostarelo/discover-crawler
        name: crawler
        volumeMounts:
        - mountPath: /local
          name: crawler-claim0
        resources: {}
      restartPolicy: Always
      volumes:
      - name: crawler-claim0
        persistentVolumeClaim:
          claimName: crawler-claim0
      initContainers:
      - name: init-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis:6379; do echo waiting for redis; sleep 2; done;']
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres:5432; do echo waiting for postgres; sleep 2; done;']
      - name: init-neo
        image: busybox
        command: ['sh', '-c', 'until nc -z neo:7474; do echo waiting for neo; sleep 2; done;']
status: {}
