apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: crawler
  name: crawler
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: crawler
    spec:
      containers:
      - env:
        - name: QUEUE_STORE_DIR
          value: ./
        - name: REDIS_HOST
          value: redis:6379
        image: kostarelo/discover-crawler
        name: crawler
        resources: {}
        volumeMounts:
        - mountPath: /src/local
          name: crawler-claim0
      restartPolicy: Always
      volumes:
      - name: crawler-claim0
        persistentVolumeClaim:
          claimName: crawler-claim0
status: {}
