apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  creationTimestamp: null
  labels:
    io.kompose.service: extraction-claim0
  name: extraction-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
