apiVersion: v1
kind: Service
metadata:
  namespace: development
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: neo
  name: neo
spec:
  ports:
  - name: "7474"
    port: 7474
    targetPort: 7474
  - name: "6477"
    port: 6477
    targetPort: 6477
  - name: "7687"
    port: 7687
    targetPort: 7687
  selector:
    io.kompose.service: neo
status:
  loadBalancer: {}
