apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  creationTimestamp: null
  labels:
    io.kompose.service: neo-claim0
  name: neo-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
