apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: neo
  name: neo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: neo
    spec:
      containers:
      - env:
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: 0.0.0.0:7687
        - name: NEO4J_dbms_connector_http_listen__address
          value: 0.0.0.0:7474
        - name: NEO4J_dbms_connector_https_listen__address
          value: 0.0.0.0:6477
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo-secret
              key: NEO4J_AUTH
        image: neo4j:3.0
        livenessProbe:
          exec:
            command:
            - curl -w %{http_code} -s --output /dev/null localhost:7474
          failureThreshold: 5
          periodSeconds: 5
          timeoutSeconds: 5
        name: discover-neo
        ports:
        - containerPort: 7474
        - containerPort: 6477
        - containerPort: 7687
        resources: {}
        volumeMounts:
        - mountPath: /plugins
          name: neo-claim0
        - mountPath: /data
          name: neo-claim1
        - mountPath: /import
          name: neo-claim2
        - mountPath: /logs
          name: neo-claim3
      restartPolicy: Always
      volumes:
      - name: neo-claim0
        persistentVolumeClaim:
          claimName: neo-claim0
      - name: neo-claim1
        persistentVolumeClaim:
          claimName: neo-claim1
      - name: neo-claim2
        persistentVolumeClaim:
          claimName: neo-claim2
      - name: neo-claim3
        persistentVolumeClaim:
          claimName: neo-claim3
status: {}
