apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-claim0
  name: postgres-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
status: {}
